language: node_js
node_js:
  - '0.12'
before_script:
  - 'export DISPLAY=:99.0'
  - 'sh -e /etc/init.d/xvfb start'
  - 'npm install -g http-server jshint protractor q'
  - 'webdriver-manager update'
  - sleep 5
script:
  - 'npm test'
